### PR TITLE
Store

### PR DESCRIPTION
**Pull request by fxpineau**
Very large refactoring to use the MOC Lib Rust internal storage to replace the ST-MOC storage
AND to also store MOCs and TimeMOCs on the Rust side (wihtout passing back and forth from Python to Rust).
Also remove some part of the code that where duplicated (like FITs reading) with MOC Lib Rust (to possibly debug only 
the Rust code, to benefits for bug solving in WASM, GUI, CLI, and MOCPy, to possibly handle larger MOCs, ...).

### CODE REVIEW

**Comment by ManonMarchand** [comment]
Hello, I did the switch to Ruff in our pre-commits. Normally once pulled you don't need to redo `pre-commit install` for the changes to be effective but i'm not 100% sure

**Comment by ManonMarchand** [comment]
And I changed also the names of workflow steps from `set up python 3.6 on ubuntu` to `set up python on ubuntu`. This avoid that we forget to update the names when we upgrade version.

**Comment by fxpineau** [comment]
> Hello, I did the switch to Ruff in our pre-commits. Normally once pulled you don't need to redo `pre-commit install` for the changes to be effective but i'm not 100% sure

FYI, it worked without `pre-commit install` :)

**Comment by bmatthieu3** [comment]
I did some fixes in the doc examples (the last one was failing due to a change of api of matplotlib.imshow). I also briefly checked the doc and added things the contributing page.

**Comment by ManonMarchand** [comment]
does this PR solve #37 ?

**Comment by bmatthieu3** [comment]
At least https://github.com/cds-astro/mocpy/issues/73 with `MOC.wcs(args)` returning a wcs centered around the moc without specifying any center nor fov

**Comment by ManonMarchand** [comment]
proposition: rename `store_index_dtype` into `_store_index_dtype` cause this sould not be exposed in the API?

**Pull request merged**
